lpnu/Controllers/EducationController.cs
using lpnu.Models;
using lpnu.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace lpnu.Controllers
{
    public class EducationController : Controller
	{
		private readonly IEducationProgramService _educationProgramService;
		private readonly ICompanyService _companyService;
		private readonly IUniversityService _universityService;
		private readonly IConferenceService _conferenceService;
		public EducationController(IEducationProgramService educationProgramService, ICompanyService companyService, IUniversityService universityService, IConferenceService conferenceService)
		{
			_educationProgramService = educationProgramService;
			_companyService = companyService;
			_conferenceService = conferenceService;
			_universityService = universityService;
		}
		public IActionResult Programs()
		{
			return View();
		}

		[Authorize(Roles = "Admin")]
		public IActionResult CreateItemForEducationProgram()
		{
			return View("~/Views/Education/AdminActions/Create/CreateItemForEducationProgram.cshtml");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> CreateItemForEducationProgram(EducationProgram programTitle)
		{
			if (ModelState.IsValid)
			{
				await _educationProgramService.AddEducationProgramAsync(programTitle);
				return RedirectToAction(nameof(Programs));
			}
			return View("~/Views/Education/AdminActions/Create/CreateItemForEducationProgram.cshtml", programTitle);
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteItemForEducationProgram(int id)
		{
			var educationProgram = await _educationProgramService.GetEducationProgramByIdAsync(id);
			if (educationProgram == null)
			{
				return NotFound();
			}
			return View("~/Views/Education/AdminActions/Delete/DeleteItemForEducationProgram.cshtml", educationProgram);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteConfirmedItemForEducationProgram(int id)
		{
			await _educationProgramService.DeleteEducationProgramAsync(id);
			return RedirectToAction(nameof(Programs));
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> EditItemForEducationProgram(int id)
		{
			var program = await _educationProgramService.GetEducationProgramByIdAsync(id);
			if (program == null)
			{
				return NotFound();
			}
			return View("~/Views/Education/AdminActions/Edit/EditItemForEducationProgram.cshtml", program);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> EditItemForEducationProgram(int id, EducationProgram program)
		{
			if (id != program.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				await _educationProgramService.UpdateEducationProgramAsync(program);
				return RedirectToAction(nameof(Programs));
			}
			return View("~/Views/Education/AdminActions/Edit/EditItemForEducationProgram.cshtml", program);
		}

		public async Task<IActionResult> Bachelor()
		{
			var bachelorsPrograms = await _educationProgramService.GetAllBachelorsProgramsAsync();
			var viewModel = new EducationProgramViewModel
			{
				BachelorsPrograms = bachelorsPrograms

			};
			return View(viewModel);
		}

		public async Task<IActionResult> Master()
		{
			var mastersPrograms = await _educationProgramService.GetAllMastersProgramsAsync();
			var viewModel = new EducationProgramViewModel
			{
				MastersPrograms = mastersPrograms

			};
			return View(viewModel);
		}

		public async Task<IActionResult> Phd()
		{
			var phdPrograms = await _educationProgramService.GetAllPhdProgramsAsync();
			var viewModel = new EducationProgramViewModel
			{
				PhdPrograms = phdPrograms

			};
			return View(viewModel);
		}

		public async Task<IActionResult> InternationalRelations()
		{
			var companies = await _companyService.GetAllCompaniesAsync();
			var conferences = await _conferenceService.GetAllConferencesAsync();
			var universities = await _universityService.GetAllUniversitiesAsync();
			var viewModel = new InternationalRelationsViewModel
			{
				Companies = companies,
				Conferences = conferences,
				Universities = universities

			};
			return View(viewModel);
		}


		[Authorize(Roles = "Admin")]
		public IActionResult CreateItemForCompany()
		{
			return View("~/Views/Education/AdminActions/Create/CreateItemForCompany.cshtml");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> CreateItemForCompany(Company company)
		{
			if (ModelState.IsValid)
			{
				await _companyService.AddCompanyAsync(company);
				return RedirectToAction(nameof(InternationalRelations));
			}
			return View("~/Views/Education/AdminActions/Create/CreateItemForCompany.cshtml", company);
		}

		[Authorize(Roles = "Admin")]
		public IActionResult CreateItemForUniversity()
		{
			return View("~/Views/Education/AdminActions/Create/CreateItemForUniversity.cshtml");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> CreateItemForUniversity(University university)
		{
			if (ModelState.IsValid)
			{
				await _universityService.AddUniversityAsync(university);
				return RedirectToAction(nameof(InternationalRelations));
			}
			return View("~/Views/Education/AdminActions/Create/CreateItemForUniversity.cshtml", university);
		}

		[Authorize(Roles = "Admin")]
		public IActionResult CreateItemForConference()
		{
			return View("~/Views/Education/AdminActions/Create/CreateItemForConference.cshtml");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> CreateItemForConference(Conference conference)
		{
			if (ModelState.IsValid)
			{
				await _conferenceService.AddConferenceAsync(conference);
				return RedirectToAction(nameof(InternationalRelations));
			}
			return View("~/Views/Education/AdminActions/Create/CreateItemForConference.cshtml", conference);
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteItemForCompany(int id)
		{
			var company = await _companyService.GetCompanyByIdAsync(id);
			if (company == null)
			{
				return NotFound();
			}
			return View("~/Views/Education/AdminActions/Delete/DeleteItemForCompany.cshtml", company);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteConfirmedItemForCompany(int id)
		{
			await _companyService.DeleteCompanyAsync(id);
			return RedirectToAction(nameof(InternationalRelations));
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteItemForUniversity(int id)
		{
			var university = await _universityService.GetUniversitiesByIdAsync(id);
			if (university == null)
			{
				return NotFound();
			}
			return View("~/Views/Education/AdminActions/Delete/DeleteItemForUniversity.cshtml", university);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteConfirmedItemForUniversity(int id)
		{
			await _universityService.DeleteUniversityAsync(id);
			return RedirectToAction(nameof(InternationalRelations));
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteItemForConference(int id)
		{
			var conference = await _conferenceService.GetConferencesByIdAsync(id);
			if (conference == null)
			{
				return NotFound();
			}
			return View("~/Views/Education/AdminActions/Delete/DeleteItemForConference.cshtml", conference);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> DeleteConfirmedItemForConference(int id)
		{
			await _conferenceService.DeleteConferenceAsync(id);
			return RedirectToAction(nameof(InternationalRelations));
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> EditItemForCompany(int id)
		{
			var company = await _companyService.GetCompanyByIdAsync(id);
			if (company == null)
			{
				return NotFound();
			}
			return View("~/Views/Education/AdminActions/Edit/EditItemForCompany.cshtml", company);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> EditItemForCompany(int id, Company company)
		{
			if (id != company.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				await _companyService.UpdateCompanyAsync(company);
				return RedirectToAction(nameof(InternationalRelations));
			}
			return View("~/Views/Education/AdminActions/Edit/EditItemForCompany.cshtml", company);
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> EditItemForUniversity(int id)
		{
			var university = await _universityService.GetUniversitiesByIdAsync(id);
			if (university == null)
			{
				return NotFound();
			}
			return View("~/Views/Education/AdminActions/Edit/EditItemForUniversity.cshtml", university);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> EditItemForUniversity(int id, University university)
		{
			if (id != university.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				await _universityService.UpdateUniversityAsync(university);
				return RedirectToAction(nameof(InternationalRelations));
			}
			return View("~/Views/Education/AdminActions/Edit/EditItemForUniversity.cshtml", university);
		}

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> EditItemForConference(int id)
		{
			var conference = await _conferenceService.GetConferencesByIdAsync(id);
			if (conference == null)
			{
				return NotFound();
			}
			return View("~/Views/Education/AdminActions/Edit/EditItemForConference.cshtml", conference);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]

lpnu/Views/Education/AdminActions/Create/CreateItemForCompany.cshtml
@model lpnu.Models.Company
@{
	ViewData["Title"] = "Create Company";
}
<div class="form-container">
	<h2>Add New Company</h2>
	<form asp-controller="Education" asp-action="CreateItemForCompany" method="post">
		<div>
			<label asp-for="Name">Company Name</label>
			<input type="text" asp-for="Name" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div>
			<label asp-for="LogoPath">Logo Path</label>
			<input type="text" asp-for="LogoPath" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="LogoPath" class="text-danger"></span>
		</div>
		<div>
			<label asp-for="FlagPath">Flag Path</label>
			<input type="text" asp-for="FlagPath" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="FlagPath" class="text-danger"></span>
		</div>
		<button type="submit">Create Company</button>
	</form>
</div>

lpnu/Views/Education/AdminActions/Create/CreateItemForConference.cshtml
@model lpnu.Models.Conference
@{
	ViewData["Title"] = "Create Conference";
}
<div class="form-container">
	<h2>Add New Conference</h2>
	<form asp-controller="Education" asp-action="CreateItemForConference" method="post">
		<div>
			<label asp-for="Title">Title</label>
			<input type="text" asp-for="Title" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="Title" class="text-danger"></span>
		</div>
		<div>
			<label asp-for="Abbreviation">Abbreviation</label>
			<input type="text" asp-for="Abbreviation" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="Abbreviation" class="text-danger"></span>
		</div>
		<button type="submit">Create Conference</button>
	</form>
</div>

lpnu/Views/Education/AdminActions/Create/CreateItemForEducationProgram.cshtml
@model lpnu.Models.EducationProgram

@{
	ViewData["Title"] = "Create Education Program";
}
<div class="form-container">
	<h2>Create Education Program</h2>
	<form asp-action="CreateItemForEducationProgram" method="post">
		<div class="form-group">
			<label asp-for="Title" class="control-label"></label>
			<input asp-for="Title" class="form-control" />
			<span asp-validation-for="Title" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Description" class="control-label"></label>
			<textarea asp-for="Description" class="form-control"></textarea>
			<span asp-validation-for="Description" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Level" class="control-label"></label>
			<select asp-for="Level" class="form-control" asp-items="Html.GetEnumSelectList<lpnu.Models.EducationLevel>()"></select>
			<span asp-validation-for="Level" class="text-danger"></span>
		</div>
		<button type="submit">Create Education Program</button>
	</form>
</div>
@section Scripts {
	<partial name="_ValidationScriptsPartial" />
	<script>
		CKEDITOR.replace('Description');
	</script>
}

lpnu/Views/Education/AdminActions/Create/CreateItemForUniversity.cshtml
@model lpnu.Models.University
@{
	ViewData["Title"] = "Create University";
}
<div class="form-container">
	<h2>Add New University</h2>
	<form asp-controller="Education" asp-action="CreateItemForUniversity" method="post">
		<div>
			<label asp-for="Name">Company Name</label>
			<input type="text" asp-for="Name" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div>
			<label asp-for="LogoPath">Logo Path</label>
			<input type="text" asp-for="LogoPath" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="LogoPath" class="text-danger"></span>
		</div>
		<div>
			<label asp-for="City">City</label>
			<input type="text" asp-for="City" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="City" class="text-danger"></span>
		</div>
		<div>
			<label asp-for="Country">Country</label>
			<input type="text" asp-for="Country" placeholder="Enter..." class="form-control" required />
			<span asp-validation-for="Country" class="text-danger"></span>
		</div>
		<button type="submit">Create Company</button>
	</form>
</div>